package utils

const (
	GOODNOTES_STANDARD_FLASHCARD_WIDTH  = 455.04
	GOODNOTES_STANDARD_FLASHCARD_HEIGHT = 588.45
	DIMENSION_TOLERANCE                 = 2.0

	QuestionKeyword = "QUESTION"
	AnswerKeyword   = "ANSWER"
)
